---
abstract: 'make simple lightweight record-like structures that make sounds like cows'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Moo: '1.006000'
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.024, CPAN::Meta::Converter version 2.150010'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Struct
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooX::Struct:
    file: lib/MooX/Struct.pm
    version: '0.020'
  MooX::Struct::Processor:
    file: lib/MooX/Struct.pm
    version: '0.020'
  MooX::Struct::Util:
    file: lib/MooX/Struct/Util.pm
    version: '0.020'
requires:
  B::Hooks::EndOfScope: '0'
  Exporter::Tiny: '0.044'
  Moo: '1.000000'
  Object::ID: '0'
  Type::Tiny: '1.000000'
  namespace::autoclean: '0.19'
  perl: '5.008'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/MooX-Struct/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooX-Struct
  homepage: https://metacpan.org/release/MooX-Struct
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moox-struct.git
version: '0.020'
x_contributors:
  - NOBODY
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
